### Matrices
In this notebook, we will go through matrix, creation and initiation, accessing elements using NumPy

Matrices act like a table with rows and columns in Python.
<br>Matrices can contain only one type of data.
<br><br>Matrices can be created using NumPy in the following ways:
* using **np.reshape(i, d, order)** where
  * **i** is **input data**
  * **d** is **required dimension** passed as a **tuple**
  * **order** is **the default behaviour of populating the data**
    * if **C**, **row-wise population**, based on the C-langugage (default behaviour)
    * if **F**, **column-wise population** based on the Fortron-language
* using **data.reshape(d)**
  * **d** is **required dimension** passed as a **tuple**
* using **np.array()**

In [1]:
import numpy as np

In [2]:
data = np.arange(0, 20)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
#using np.reshape()
mat1 = np.reshape(data, (5, 4)) #by default, row-wise population
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
mat1 = np.reshape(data, (5, 4), order='C') #C-like population
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [5]:
mat2 = np.reshape(data, (5, 4), order='F') #Fortron-like population
mat2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [6]:
#using data.reshape()
mat3 = data.reshape((5,4))
mat3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
#using np.array()
list1 = ['Have', 'a', 'good', 'day']
list2 = list(range(2, 6))
mat4 = np.array([list1, list2]) #the second list, which contains numbers are modified to be strings
mat4

array([['Have', 'a', 'good', 'day'],
       ['2', '3', '4', '5']], dtype='<U4')

**accessing matrix elements**

In [8]:
mat1[2,3]

11

In [9]:
mat1[2][3]

11

In [10]:
mat2[1,2]

11

In [11]:
mat2[1][2]

11